import dotenv from 'dotenv';
import { parseResumeWithGemini, analyzeResumeWithGemini } from './services/gemini.js';

dotenv.config();

async function testRealFlow() {
  console.log('====================================================');
  console.log('🚀 TESTING LIVE GEMINI API RESUME EXTRACTION & AUDIT');
  console.log('====================================================\n');

  const sampleRawText = `
ADITYA SHARMA
Email: aditya.sharma@example.com | Phone: +1-555-019-2834 | San Francisco, CA
LinkedIn: linkedin.com/in/adityasharma | GitHub: github.com/adityasharma

PROFESSIONAL SUMMARY
Results-driven Software Engineer with 3+ years of experience building high-concurrency web applications using TypeScript, React, Node.js, PostgreSQL, and Google Cloud Platform. Skilled in full-stack architecture, microservices, and AI integrations.

WORK EXPERIENCE
Senior Full Stack Developer | TechNova Solutions | Jan 2024 – Present
- Designed and launched scalable REST APIs and WebSocket services handling 50,000+ daily active users with 99.95% uptime.
- Led migration of legacy monolith to Node.js microservices, reducing server response latencies by 45%.
- Implemented real-time analytics dashboard with React, Tailwind CSS, and Redis caching.

Software Engineer | CodeCraft Systems | Jun 2022 – Dec 2023
- Built responsive user interfaces and state management systems using React, Redux Toolkit, and GraphQL.
- Reduced bundle size by 35% through code-splitting, tree-shaking, and lazy loading strategies.

SKILLS
Programming: TypeScript, JavaScript, Python, SQL, HTML5, CSS3
Frameworks & Libraries: React, Node.js, Express, Next.js, Tailwind CSS, Prisma
Databases & Cloud: PostgreSQL, Redis, Google Cloud Platform (GCP), AWS S3, Docker, Git

EDUCATION
Bachelor of Science in Computer Science | California State University | 2018 – 2022
`;

  console.log('Step 1: Running parseResumeWithGemini()...\n');
  const parsed = await parseResumeWithGemini(sampleRawText, 'Software Engineer');

  console.log('\n--- PARSE RESULT METADATA ---');
  console.log('Source:', parsed.source);
  console.log('Model Used:', parsed.modelUsed);
  console.log('Candidate Name:', parsed.contact.name);
  console.log('Skills Extracted:', parsed.skills.slice(0, 5));

  console.log('\nStep 2: Running analyzeResumeWithGemini()...\n');
  const jdText = `We are looking for a Senior Software Engineer proficient in React, Node.js, TypeScript, PostgreSQL, and cloud deployments to build high-performance web platforms.`;
  
  const analysis = await analyzeResumeWithGemini(parsed, 'Software Engineer', jdText);

  console.log('\n--- ANALYSIS RESULT METADATA & SCORES ---');
  console.log('Source:', analysis.source);
  console.log('Model Used:', analysis.modelUsed);
  console.log('AI Content Quality Score:', analysis.aiQualityScore);
  console.log('Job Description Match Score:', analysis.matchScore);
  console.log('Overall Summary:', analysis.overallSummary);
  console.log('\n--- REWRITE SUGGESTIONS (First 2) ---');
  analysis.rewriteSuggestions.slice(0, 2).forEach((s, i) => {
    console.log(`\nSuggestion #${i + 1}:`);
    console.log(`Original: "${s.original}"`);
    console.log(`Rewritten: "${s.rewritten}"`);
    console.log(`Reasoning: ${s.reasoning}`);
  });

  console.log('\n====================================================');
  if (parsed.source === 'ai' && analysis.source === 'ai') {
    console.log(`✅ SUCCESS PROOF: Both extraction and analysis were generated by LIVE Gemini API (${analysis.modelUsed})!`);
  } else {
    console.log('⚠️ Warning: Fallback engine triggered.');
  }
  console.log('====================================================');
}

testRealFlow().catch(console.error);
